version: "3.7"
services:
    test_app:
        container_name: test_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:8000
        command: bash -c "composer install && php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
        depends_on:
            - test_db
        networks:
            - my_network

    test_db:
        container_name: test_db
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "33062:3306"
        networks:
            - my_network

    test_nginx:
        container_name: test_nginx
        image: nginx:alpine
        ports:
            - 89:80
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - my_network

networks:
    my_network:
